import { SectionHero } from '@/components/sections/SectionHero';
import { CTASection } from '@/components/sections/CTASection';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { JsonLd } from '@/components/seo/JsonLd';
import { generatePageMetadata } from '@/lib/metadata';

export const metadata = generatePageMetadata({
  title: 'Incentives & Opportunity Zone',
  description:
    'Commerce, Texas offers a comprehensive incentives toolkit including land at no cost, tax abatements, forgivable loans, TIRZ, Enterprise Zone, and federal Opportunity Zone benefits.',
  path: '/why-commerce/incentives',
});

const incentives = [
  {
    title: 'Land at No Cost',
    description:
      'The Commerce EDC owns shovel-ready industrial tracts and can provide land at no cost to qualifying projects that meet job creation and capital investment benchmarks.',
    category: 'Real Estate',
  },
  {
    title: 'Spec Building Programs',
    description:
      'Purpose-built spec facilities can be developed to meet the specific requirements of incoming businesses, reducing time-to-occupancy and upfront capital outlay.',
    category: 'Real Estate',
  },
  {
    title: 'Infrastructure Support',
    description:
      'The EDC can fund or co-fund infrastructure improvements including streets, water, sewer, and gas extensions to serve new and expanding businesses.',
    category: 'Infrastructure',
  },
  {
    title: 'Forgivable & Low-Interest Loans',
    description:
      'Performance-based forgivable loans and below-market-rate financing are available to companies that meet agreed-upon job creation and capital investment targets.',
    category: 'Financial',
  },
  {
    title: 'Cash for Jobs & Capital Investment',
    description:
      'Direct cash incentives tied to new job creation and capital investment allow businesses to offset startup and expansion costs as they grow in Commerce.',
    category: 'Financial',
  },
  {
    title: 'Building Renovation Assistance',
    description:
      'Financial assistance is available for companies renovating or repurposing existing commercial or industrial buildings in Commerce, helping revitalize the community while reducing build-out costs.',
    category: 'Real Estate',
  },
  {
    title: 'Job Training Programs',
    description:
      'In partnership with East Texas A&M University and regional workforce boards, the EDC helps companies access customized job training and skills development programs to build a qualified local workforce.',
    category: 'Workforce',
  },
  {
    title: 'Tax Reinvestment Zone (TIRZ)',
    description:
      'Commerce has established Tax Reinvestment Zones that capture incremental tax revenue generated by new development and reinvest it in infrastructure, public improvements, and economic development within the zone.',
    category: 'Tax',
  },
  {
    title: 'Tax Abatement',
    description:
      'Qualifying businesses may receive property tax abatements on new improvements for a defined period, reducing operating costs during the critical early years of a project.',
    category: 'Tax',
  },
  {
    title: 'Enterprise Zone',
    description:
      'Commerce participates in the Texas Enterprise Zone Program, which provides state sales and use tax refunds to qualifying businesses that create jobs and make capital investments in designated areas.',
    category: 'Tax',
  },
  {
    title: '4A Sales Tax Projects',
    description:
      'As a Type A (4A) economic development corporation, the Commerce EDC uses dedicated sales tax revenue to fund projects that create and retain primary jobs — including manufacturing, distribution, research, and corporate headquarters.',
    category: 'Financial',
  },
];

const categoryColors: Record<string, 'amber' | 'green' | 'navy' | 'default'> = {
  'Real Estate': 'amber',
  Infrastructure: 'navy',
  Financial: 'green',
  Workforce: 'default',
  Tax: 'navy',
};

export default function IncentivesPage() {
  return (
    <>
      <JsonLd
        data={{
          '@context': 'https://schema.org',
          '@type': 'WebPage',
          name: 'Incentives & Opportunity Zone - Commerce, Texas',
          description:
            'Comprehensive business incentives including land, tax abatements, loans, and federal Opportunity Zone benefits.',
          url: 'https://commerceedc.com/why-commerce/incentives',
        }}
      />

      <SectionHero
        title="Incentives & Opportunity Zone"
        subtitle="A comprehensive toolkit designed to reduce costs, accelerate timelines, and reward job creation and capital investment."
        breadcrumbs={[
          { label: 'Home', href: '/' },
          { label: 'Why Commerce', href: '/why-commerce' },
          { label: 'Incentives & OZ' },
        ]}
      />

      {/* Overview */}
      <section className="bg-cream py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-4">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="font-heading text-3xl font-bold text-navy sm:text-4xl">
              Built to Compete
            </h2>
            <p className="mt-6 text-lg leading-relaxed text-gray-700">
              The Commerce Economic Development Corporation offers one of the most
              competitive incentive packages in Northeast Texas. Every incentive is
              performance-based and tailored to the specific needs of the project,
              ensuring that public investment generates measurable results for both
              the company and the community.
            </p>
          </div>
        </div>
      </section>

      {/* Incentives Grid */}
      <section className="bg-white py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-4">
          <h2 className="font-heading text-3xl font-bold text-navy sm:text-4xl">
            Available Incentives
          </h2>
          <p className="mt-4 max-w-2xl text-gray-600">
            All incentives are negotiated on a project-by-project basis and are tied to
            job creation, capital investment, and other performance criteria.
          </p>
          <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {incentives.map((incentive) => (
              <Card key={incentive.title}>
                <div className="flex items-start justify-between">
                  <h3 className="font-heading text-lg font-bold text-navy">
                    {incentive.title}
                  </h3>
                  <Badge variant={categoryColors[incentive.category] || 'default'}>
                    {incentive.category}
                  </Badge>
                </div>
                <p className="mt-3 text-sm text-gray-600 leading-relaxed">
                  {incentive.description}
                </p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Opportunity Zone */}
      <section className="bg-navy py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-4">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-start">
            <div>
              <Badge variant="green" className="text-sm px-4 py-1">
                Federal Designation
              </Badge>
              <h2 className="mt-4 font-heading text-3xl font-bold text-white sm:text-4xl">
                Opportunity Zone
              </h2>
              <p className="mt-6 text-lg leading-relaxed text-gray-200">
                Commerce is home to a federally designated Opportunity Zone (OZ),
                created under the Tax Cuts and Jobs Act of 2017. Opportunity Zones
                are designed to spur economic development and job creation in
                distressed communities by providing tax benefits to investors who
                invest eligible capital gains into Qualified Opportunity Funds.
              </p>
              <p className="mt-4 text-lg leading-relaxed text-gray-200">
                Investors who deploy capital gains into a Qualified Opportunity Fund
                can benefit from tax deferral on the original gain, potential
                reduction in the taxable amount, and elimination of capital gains
                tax on appreciation if the investment is held for at least 10 years.
              </p>
            </div>
            <div>
              <div className="rounded-xl bg-navy-light border border-gray-600 p-6">
                <h3 className="font-heading text-xl font-bold text-white">
                  OZ Investor Benefits
                </h3>
                <ul className="mt-4 space-y-4">
                  {[
                    {
                      benefit: 'Tax Deferral',
                      detail:
                        'Defer federal tax on eligible capital gains invested in a Qualified Opportunity Fund until the earlier of the date the investment is sold or December 31, 2026.',
                    },
                    {
                      benefit: 'Step-Up in Basis',
                      detail:
                        'If the investment is held for at least 5 years, the investor receives a 10% step-up in basis on the deferred gain.',
                    },
                    {
                      benefit: 'Tax-Free Appreciation',
                      detail:
                        'If the investment is held for at least 10 years, any appreciation in the value of the Opportunity Fund investment is permanently excluded from taxable income.',
                    },
                  ].map((item) => (
                    <li key={item.benefit}>
                      <p className="font-semibold text-amber">{item.benefit}</p>
                      <p className="mt-1 text-sm text-gray-100">{item.detail}</p>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Census Tract Details */}
      <section className="bg-cream py-16 sm:py-20">
        <div className="mx-auto max-w-7xl px-4">
          <div className="mx-auto max-w-3xl text-center">
            <h2 className="font-heading text-3xl font-bold text-navy sm:text-4xl">
              Opportunity Zone Census Tract
            </h2>
            <p className="mt-6 text-lg leading-relaxed text-gray-700">
              Commerce&apos;s designated Opportunity Zone encompasses key industrial and
              commercial areas within the city. Specific census tract boundaries and
              mapping details are being finalized and will be published here.
            </p>
            <p className="mt-4 text-gray-500 italic">
              Census tract details to be determined. Contact the Commerce EDC for the
              most current OZ boundary information.
            </p>
          </div>
        </div>
      </section>

      <CTASection
        title="Let Us Build Your Incentive Package"
        description="Every project is unique. Contact the Commerce EDC for a confidential evaluation of incentives available for your business."
        buttonText="Contact Us"
        buttonHref="/contact"
        variant="amber"
      />
    </>
  );
}
